@HotelListing.API_HostAddress = https://localhost:7001



GET {{HotelListing.API_HostAddress}}/api/hotels

###

@id=0
GET {{HotelListing.API_HostAddress}}/api/hotels/3

###


POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json
{ "id" : 4, 
  "name" : "Tiny Plaza", 
  "address" : "999 Main St", 
  "rating" : 4 
}


###

PUT {{HotelListing.API_HostAddress}}/api/hotels/1
Content-Type: application/json
{ "id" : 1, 
  "name" : "Mickey", 
  "address" : "888 Main St", 
  "rating" : 1
}

###

DELETE {{HotelListing.API_HostAddress}}/api/hotels/1

###
