@HotelListing.API_HostAddress = https://localhost:7001


GET {{HotelListing.API_HostAddress}}/api/hotels

###

@id=3
GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json
{
  
  "name": "Hotel Ranchi",
  "address": "Peace Rd",
  "rating": 3,
  "countryId": 4
}

###
